import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <head>
        <title>ThumbSnatch - Capturez vos miniatures YouTube</title>
        <meta
          name="description"
          content="Transformez chaque lien YouTube en une miniature haute qualité avec ThumbSnatch."
        />
        <meta
          name="keywords"
          content="YouTube thumbnail, capture miniature YouTube, télécharger miniature vidéo"
        />
        <meta name="author" content="Votre Nom" />
        <meta
          property="og:title"
          content="ThumbSnatch - Miniatures YouTube instantanées"
        />
        <meta
          property="og:description"
          content="Obtenez des miniatures haute qualité à partir de n'importe quel lien YouTube."
        />
        <meta property="og:image" content="/public/thumbnail-preview.png" />
        <meta property="og:url" content="https://yourdomain.com" />
        <meta name="twitter:card" content="summary_large_image" />
      </head>
      <body>{children}</body>
    </html>
  );
}
